version: "3"

services:
  ckan:
    build: 
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      # debug locally
      # - /home/hudson/dev/UNC/ckanext-siu-harvester:/srv/app/src_extensions/ckanext-siu-harvester
      

  db:
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
