services:
  ckan:
    build:
      context: ckan/
      dockerfile: Dockerfile
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      # - /home/user/myfolder/ckanext-siu-harvester:/srv/app/src/ckanext-siu-harvester
      # - /home/user/myfolder/ckanext-siu-harvester:/srv/app/src_extensions/ckanext-siu-harvester
      # - /home/user/myfolder/ckanext-datasetpreview:/srv/app/src_extensions/ckanext-datasetpreview
      # - /home/user/myfolder/pySIUdata/siu_data:/usr/lib/python3.8/site-packages/siu_data
      # - /home/user/myfolder/ckanext-harvest:/srv/app/src_extensions/ckanext-harvest

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

volumes:
  ckan_storage:
  pg_data:
  solr_data:
