name: Build and publish develop docker-ckan image version
on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build develop version for UNCKAN
        uses: docker/build-push-action@v2
        with:
          context: docker/ckan
          file: docker/ckan/Dockerfile
          push: true
          tags: avdata99/unckan:dev
