name: Build and publish docker-ckan image
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ckan-base 2.8
        uses: docker/build-push-action@v2
        with:
          context: ckan-2.8
          file: ckan-2.8/Dockerfile
          push: true
          tags: avdata99/ckan-env:ckan28
      - name: Build ckan-base 2.9
        uses: docker/build-push-action@v2
        with:
          context: ckan-2.9/ckan
          file: ckan-2.9/ckan/Dockerfile
          push: true
          tags: avdata99/ckan-env:ckan29
