name: Test Build
on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read CKAN_UNI_VERSION from docker/ckan/files/env/base.env
        run: |
          echo "CKAN_UNI_VERSION=$(grep CKAN_UNI_VERSION docker/ckan/files/env/base.env | cut -d '=' -f2)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build develop UNCKAN ver ${{ CKAN_UNI_VERSION }}
        uses: docker/build-push-action@v2
        with:
          context: docker/ckan
          file: docker/ckan/Dockerfile
          push: false
